default:
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('DATABASE_PATH', '../data/database.duckdb') }}"
      threads: 16
      settings:
        enable_object_cache: true
        enable_http_metadata_cache: true
  target: dev

config:
  send_anonymous_usage_stats: False
  use_colors: True
