version: 2

sources:
  - name: web
    tables:
      - name: energy
        description: Key energy metrics maintained by Our World in Data
        meta:
          source: https://ourworldindata.org/energy
          external_location: https://raw.githubusercontent.com/owid/energy-data/master/owid-energy-data.csv
      - name: co2_global_trend
        description: Trends in Atmospheric Carbon Dioxide
        meta:
          source: https://gml.noaa.gov
          external_location: https://gml.noaa.gov/webdata/ccgg/trends/co2/co2_trend_gl.csv

  - name: public
    tables:
      - name: raw_threatened_animal_species
        meta:
          dagster:
            asset_key: ["raw_threatened_animal_species"]
      - name: raw_owid_co2_data
        meta:
          dagster:
            asset_key: ["raw_owid_co2_data"]
