[default]
_note_1 = "Notice the structure of this file is the same as alto.toml"
_note_2 = "Anything in here is merged into the main config file"

[default.taps.tap-carbon-intensity]
some_secret = "**I will be merged into alto.toml**"

[default.targets.target-jsonl]
other_secret = "**use this file for secret management**"
final_secret = "**exclude it from source control**"
