#!/usr/bin/env python3
"""
Generate torrent files for datadex datasets with HuggingFace webseeds.

This script creates torrent files for the datasets generated by datadex,
using HuggingFace URLs as webseeds to provide HTTP fallback download options.
"""

import os
from pathlib import Path
from typing import List

import torf


def create_torrent_with_webseed(
    file_path: Path,
    output_dir: Path,
    webseed_urls: List[str],
    announce_urls: List[str] = None,
    comment: str = None,
) -> Path:
    """
    Create a torrent file with webseeds for a given dataset file.
    
    Args:
        file_path: Path to the dataset file
        output_dir: Directory to save the torrent file
        webseed_urls: List of HTTP URLs to use as webseeds
        announce_urls: List of BitTorrent tracker URLs (optional)
        comment: Comment to include in the torrent (optional)
    
    Returns:
        Path to the created torrent file
    """
    if not file_path.exists():
        raise FileNotFoundError(f"Dataset file not found: {file_path}")
    
    # Create torrent object
    torrent = torf.Torrent(
        path=file_path,
        comment=comment or f"Datadex dataset: {file_path.name}",
        created_by="datadex torrent generator",
        webseeds=webseed_urls,
        trackers=announce_urls or [],
    )
    
    # Generate torrent
    torrent.generate()
    
    # Save torrent file
    output_dir.mkdir(parents=True, exist_ok=True)
    torrent_path = output_dir / f"{file_path.stem}.torrent"
    torrent.write(torrent_path)
    
    return torrent_path


def create_wdi_torrent() -> Path:
    """Create torrent for World Development Indicators dataset."""
    dataset_path = Path("data/world_development_indicators/world_development_indicators.parquet")
    output_dir = Path("data/world_development_indicators/")
    
    webseed_urls = [
        "https://huggingface.co/datasets/datonic/world_development_indicators/resolve/main/data/world_development_indicators.parquet"
    ]
    
    # Public BitTorrent trackers for broader distribution
    announce_urls = [
        "udp://tracker.openbittorrent.com:80",
        "udp://tracker.opentrackr.org:1337",
        "udp://tracker.coppersurfer.tk:6969",
        "udp://tracker.leechers-paradise.org:6969",
    ]
    
    comment = """World Development Indicators (WDI) dataset from the World Bank.
    
This dataset contains cross-country comparable data on development indicators.
Generated by datadex and available via HuggingFace webseed fallback.
    
Source: https://github.com/datonic/datadex
HuggingFace: https://huggingface.co/datasets/datonic/world_development_indicators"""
    
    return create_torrent_with_webseed(
        file_path=dataset_path,
        output_dir=output_dir,
        webseed_urls=webseed_urls,
        announce_urls=announce_urls,
        comment=comment,
    )


def create_owid_torrent() -> Path:
    """Create torrent for OWID indicators dataset."""
    dataset_path = Path("data/owid_indicators/owid_indicators.parquet")
    output_dir = Path("data/owid_indicators/")
    
    webseed_urls = [
        "https://huggingface.co/datasets/datonic/owid_indicators/resolve/main/data/owid_indicators.parquet"
    ]
    
    # Public BitTorrent trackers for broader distribution
    announce_urls = [
        "udp://tracker.openbittorrent.com:80",
        "udp://tracker.opentrackr.org:1337",
        "udp://tracker.coppersurfer.tk:6969",
        "udp://tracker.leechers-paradise.org:6969",
    ]
    
    comment = """Our World in Data (OWID) indicators dataset.
    
This dataset contains energy and CO2 emission indicators.
Generated by datadex and available via HuggingFace webseed fallback.
    
Source: https://github.com/datonic/datadex
HuggingFace: https://huggingface.co/datasets/datonic/owid_indicators"""
    
    return create_torrent_with_webseed(
        file_path=dataset_path,
        output_dir=output_dir,
        webseed_urls=webseed_urls,
        announce_urls=announce_urls,
        comment=comment,
    )


def main() -> None:
    """Generate torrent files for all datasets."""
    print("Creating torrent files for datadex datasets...")
    
    # Create WDI torrent
    try:
        wdi_torrent = create_wdi_torrent()
        print(f"✓ Created WDI torrent: {wdi_torrent}")
    except FileNotFoundError as e:
        print(f"⚠ Skipping WDI torrent: {e}")
    
    # Create OWID torrent
    try:
        owid_torrent = create_owid_torrent()
        print(f"✓ Created OWID torrent: {owid_torrent}")
    except FileNotFoundError as e:
        print(f"⚠ Skipping OWID torrent: {e}")
    
    print("Torrent generation complete!")


if __name__ == "__main__":
    main()