name: CI

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 */3 * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    env:
      IUCN_REDLIST_TOKEN: ${{ secrets.IUCNREDLIST_TOKEN }}
      HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
      AEMET_API_TOKEN: ${{ secrets.AEMET_API_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
      - name: Install Python 3.12
        run: uv python install 3.12
      - name: Run
        run: |
          make run
      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: pre-release
      - name: Render
        run: |
          make render
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: fbe814d4a37d3d3d7fcfeec0ab929ff6
          projectName: datadex
          directory: portal/.quarto/output
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
