version: 2

sources:
  - name: github
    tables:
      - name: yellow_taxi_trips
        meta:
          external_location: https://raw.githubusercontent.com/pablobarbera/data-science-workshop/master/modeling-viz/taxi-trips.csv
      - name: energy
        meta:
          external_location: https://raw.githubusercontent.com/owid/energy-data/master/owid-energy-data.csv
  - name: carbon_intensity
    tables:
      - name: entry
        meta:
          external_location: read_json_auto("output/carbon_intensity/entry-*.jsonl")
      - name: generationmix
        meta:
          external_location: read_json_auto("output/carbon_intensity/generationmix-*.jsonl")
      - name: region
        meta:
          external_location: read_json_auto("output/carbon_intensity/region-*.jsonl")
